
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 50;
  public static final int GTEQ = 39;
  public static final int MULT = 10;
  public static final int CHAR = 4;
  public static final int LTEQ = 38;
  public static final int LPAREN = 15;
  public static final int INT = 3;
  public static final int MINUS = 32;
  public static final int STATIC = 21;
  public static final int RPAREN = 16;
  public static final int BOOLEAN_LITERAL = 48;
  public static final int OROR = 43;
  public static final int CHARACTER_LITERAL = 49;
  public static final int NOT = 33;
  public static final int SEMICOLON = 9;
  public static final int LT = 36;
  public static final int ILLEGAL_CHARACTER = 45;
  public static final int COMMA = 11;
  public static final int CLASS = 18;
  public static final int ANDAND = 42;
  public static final int DIV = 34;
  public static final int PLUS = 31;
  public static final int NULL_LITERAL = 52;
  public static final int IF = 26;
  public static final int THIS = 23;
  public static final int DOT = 8;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 29;
  public static final int SUPER = 24;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int EQEQ = 40;
  public static final int MOD = 35;
  public static final int VOID = 22;
  public static final int EQ = 14;
  public static final int LBRACK = 6;
  public static final int COLON = 17;
  public static final int FLOATING_POINT_LITERAL = 47;
  public static final int LBRACE = 12;
  public static final int ELSE = 27;
  public static final int RBRACK = 7;
  public static final int WHILE = 28;
  public static final int FLOAT = 5;
  public static final int PUBLIC = 20;
  public static final int RBRACE = 13;
  public static final int EXTENDS = 19;
  public static final int QUESTION = 44;
  public static final int AT = 25;
  public static final int GT = 37;
  public static final int NOTEQ = 41;
  public static final int IDENTIFIER = 51;
  public static final int INTEGER_LITERAL = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "INT",
  "CHAR",
  "FLOAT",
  "LBRACK",
  "RBRACK",
  "DOT",
  "SEMICOLON",
  "MULT",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "EQ",
  "LPAREN",
  "RPAREN",
  "COLON",
  "CLASS",
  "EXTENDS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "THIS",
  "SUPER",
  "AT",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "NEW",
  "PLUS",
  "MINUS",
  "NOT",
  "DIV",
  "MOD",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "EQEQ",
  "NOTEQ",
  "ANDAND",
  "OROR",
  "QUESTION",
  "ILLEGAL_CHARACTER",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "NULL_LITERAL"
  };
}

